# Generated by Django 5.0.6 on 2025-02-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blockeddevice_blockedip'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineusers',
            name='old_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
