# Generated by Django 5.0.6 on 2025-02-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_offlineusers_old_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineusers',
            name='new_user',
            field=models.BooleanField(default=False),
        ),
    ]
