# Generated by Django 5.0.6 on 2025-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_offlineusers_new_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offlineusers',
            name='new_user',
            field=models.BooleanField(default=True),
        ),
    ]
