# Generated by Django 5.0.6 on 2025-02-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_offlineusers_new_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineusers',
            name='last_added_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
